
export const categoryConstants = {
    GET_ALL_CATEGORYS_REQUEST: 'GET_ALL_CATEGORYS_REQUEST',
    GET_ALL_CATEGORYS_SUCCESS: 'GET_ALL_CATEGORYS_SUCCESS',
    GET_ALL_CATEGORYS_FAILURE: 'GET_ALL_CATEGORYS_FAILURE',
    ADD_NEW_CATEGORY_REQUEST: 'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS: 'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE: 'ADD_NEW_CATEGORY_FAILURE'
}


